### ISSUE TITLE
Missing text: is on GitHub

### ISSUE THREAD

**Issue by onyoo** [learn-co-curriculum/js-libraries-readme#2]
I was going to add the text by hand, but realized that I would probably screw-up the formatting. Anyway, the text is on the student GitHub account and links are working, the text is just not on learn.co:
https://github.com/learn-co-students/js-libraries-readme-v-000

<img width="1218" alt="screen shot 2016-02-01 at 8 12 14 pm" src="https://cloud.githubusercontent.com/assets/14326883/12728119/9b0657cc-c920-11e5-8625-de556137fa17.png">

No biggie.

**Comment by AnnJohn** [comment]
thanks @onyoo. This looks like a product bug- we'll fix this soon.

**Comment by AnnJohn** [comment]
this has been fixed- thanks again for raising the issue.
